import 'dart:ui';

class Resep {
  int? menuId;
  String? menuImage;
  String? menuName;
  String? menuPortion;
  String? menuPrice;
  String? menuPreference;
  String? menuDescription;
  String? menuDuration;
  List<String>? menuIngredients;
  List<String>? menuTools;
  String? menuReview;
  List<String>? menuProcedure;

  Resep({
    required this.menuId,
    required this.menuImage,
    required this.menuName,
    required this.menuPortion,
    required this.menuPrice,
    required this.menuDuration,
    required this.menuPreference,
    required this.menuDescription,
    required this.menuIngredients,
    required this.menuTools,
    required this.menuReview,
    required this.menuProcedure,
  });
}

List<Resep> listResep = [
  Resep(
      menuId: 0,
      menuImage: 'assets/images/foods/imagefood1.png',
      menuName: 'Grilled Salmon',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp40.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '40 min',
      menuDescription:
          'Di samping menjadi salah satu sumber protein yang berkualitas tinggi, ikan salmon juga kaya akan asam lemak omega-3. Asam lemak omega-3 sangat berguna bagi kesehatan jantung, otak, dan organ tubuh lainnya. Selain itu rasanya lezat dan mudah diolah.',
      menuIngredients: [
        '4 potong (@ 200 g) fillet ikan salmon',
        '1 sdt garam',
        '1 sdt merica hitam butiran, gerus kasar',
        '1 sdt merica hitam butiran, gerus kasar',
        '2 sdm minyak zaitun',
        '2 sdm mentega',
        '4 siung bawang putih, iris tips',
        '4 sdm air jeruk lemon'
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur'],
      menuReview: '4,8',
      menuProcedure: ['1. Cuci Semua Sayur', '']),
  Resep(
      menuId: 1,
      menuImage: 'assets/images/foods/resep/dagingsayur1.png',
      menuName: 'Tumis Daging dan Sayur',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp36.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '42 min',
      menuDescription:
          'Ingin membuat menu makan dengan bahan daging sapi? Tumis sayur daging sapi ini mungkin bisa dicoba untuk menu hidangan makan bersama keluarga.',
      menuIngredients: [
        '1/2 kg daging sapi',
        '1 ikat sawi',
        '2 buah wortel',
        '1/4 bagian kubis',
        '1/4 bagian brokoli',
        '1/4 bagian kol',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur'],
      menuReview: '4,1',
      menuProcedure: [
        '1. Cuci bersih daging, dan rebus hingga empuk.',
        '2. Jika daging sudah matang, potong daging sesuai selera. Jangan terlalu tebal ataupun telalu tipis.',
        '3. Kupas, wortel dan potong melingkar. Potong-potong pula kubis dan sawi sesuai selera.',
        '4. Potong tipis bawang merah, bawang putih, cabai.',
        '5. Tumis semua bumbu dengan minyak secukupnya, gunakan api sedang.',
        '6. Jika bumbu sudah beraroma masukkan 300 ml air, daging, dan sayuran. Biarkan kuah meresap ke dalam daging.',
        '7. Bila sudah matang, matikan kompor dan sajikan tumis sayur daging sapi.'
      ]),
  Resep(
      menuId: 2,
      menuImage: 'assets/images/foods/resep/dagingsayur2.png',
      menuName: 'Teriyaki',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp38.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '30 min',
      menuDescription:
          'Hidangan ini terbuat dari daging yang direndam dengan saus teriyaki, kecap asin, kecap manis, dan bahan-bahan lainnya. Saus teriyaki memiliki cita rasa yang lezat, perpaduan rasa asin dan manis. Di Jepang, saus teriyaki sendiri sebenarnya mengandung sake.',
      menuIngredients: [
        'Iris tipis daging sapi 200 gram',
        'Biji wijen disangrai 2 sdm ',
        'Bawang bombay iris 1/2 butir',
        'Daun bawang, iris halus - 1 batang',
        'Margarin / mentega - 2 sdm',
        'Bawang putih, parut - 2 siung',
        'Saus teriyaki - 2 sdm',
        'Kecap asin - 1 sdm',
        'Kecap manis - 1 sdm',
        'Saus tiram - 1 sdm',
        'Lada hitam - 1 sdt',
        'Gula - 1 sdt',
        'Kaldu bubuk - 1 sdt',
        'Garam - 1/2 sdt',
        'Saus tomat - 1 sdt',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci', 'Sendok'],
      menuReview: '4,2',
      menuProcedure: [
        '1. Campur rata semua bahan bumbu rendaman.',
        '2. Masukkan daging dalam bumbu rendaman, aduk hingga merata. Diamkan dalam kulkas selama 1 malam. Sisihkan.',
        '3. Panaskan margarin. Tumis bawang bombay hingga wangi.',
        '4. Masukkan daging sambil diaduk-aduk cepat hingga berubah warna. Angkat.',
        '5. Taburi daging dengan biji wijen dan daun bawang.',
        '6. Siap disajikan.',
      ]),
  Resep(
      menuId: 3,
      menuImage: 'assets/images/foods/resep/dagingsayur3.png',
      menuName: 'Lapis Daging Sapi',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp46.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '50 min',
      menuDescription:
          'Daging lapis adalah sajian makanan yang diadaptasi dari kuliner Belanda manis dan gurih. Hidangan ini sangat cocok disantap dengan nasi hangat sebagai menu harian, baik makan siang atau makan malam. Bagi Anda pecinta olahan daging, tentu menu lezat yang satu ini wajib Anda coba.',
      menuIngredients: [
        'Iris tipis daging sapi 200 gram',
        'Biji wijen disangrai 2 sdm ',
        'Bawang bombay iris 1/2 butir',
        'Daun bawang, iris halus - 1 batang',
        'Margarin / mentega - 2 sdm',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,9',
      menuProcedure: [
        '1. Iris pipih daging dengan memotong serat.',
        '2. Campur bumbu halus dan daging menjadi satu.',
        '3. Panaskan minyak sedikit, tumis daging sampai berubah warna, tambahkan air.',
        '4. Masukkan bumbu lengkuas, batang serai, daun jeruk, kayu manis, telur dan kecap.',
        '5. Masak sampai daging empuk, agar daging lebih empuk dan bumbu meresap.',
        '6. Tunggu sampai air berkurang. Tambahkan gula dan garam.',
        '7. Koreksi rasa, matikan api. Siap disajikan.',
      ]),
  Resep(
      menuId: 4,
      menuImage: 'assets/images/foods/resep/dagingsayur4.png',
      menuName: 'Daging Sapi Asam Manis',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp22.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '35 min',
      menuDescription:
          'Ketika persediaan daging kurban melimpah, ada banyak cara membuatnya menjadi masakan spesial di Hari Raya Idul Adha. Satu di antara resep yang direkomendasikan yaitu membuatnya menjadi masakan daging sapi asam manis.',
      menuIngredients: [
        '500 gram daging sapibagian sengkel potong-potong',
        '500 ml santan kental dicampur dengan air 1 liter',
        '3 keping gula merah',
        '10 ml air asam jawa',
        '1 sdt bumbu kaldu jamur',
        '2 batang serai',
        '5 lembar daun salam',
        '3 ruas jari lengkuas, geprek',
        '3 butir kemiri',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,2',
      menuProcedure: [
        '1. Haluskan bawang merah, bawang putih, kemiri, dan ketumbar.',
        '2. Rebus santan sampai mendidih dan masukkan bumbu halus, daging, parutan gula merah, air asam jawa, kaldu jamur, dan aduk rata. Masukkan serai, daun salam, dan lengkuas.',
        '3. Masak terus dalam api kecil sambil diaduk perlahan, masak terus sampai cairan menyusut, koreksi rasa.',
        '4. Beri taburan bawang goreng, nikmati selagi hangat.',
      ]),
  Resep(
      menuId: 5,
      menuImage: 'assets/images/foods/resep/dagingsayur5.png',
      menuName: 'Bistik Sapi',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp42.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '40 min',
      menuDescription:
          'Olahan daging sapi saus asam manis sepertinya sudah terdengar biasa, tapi beda halnya bila disajikan di dalam kelapa muda. My Thai, restoran masakan Thailand di Bogor, menyajikan daging sapi saus asam manis di dalam batok kelapa. Olahan tersebut dinamakan Sapi dalam Kelapa.',
      menuIngredients: [
        '5 siung bawang putih',
        '1/2 sdt lada bubuk',
        '500 gram daging sapibagian sengkel potong-potong',
        '500 ml santan kental dicampur dengan air 1 liter',
        '3 keping gula merah',
        '10 ml air asam jawa',
        '1 sdt bumbu kaldu jamur',
        '2 batang serai',
        '5 lembar daun salam',
        '3 ruas jari lengkuas, geprek',
        '3 butir kemiri',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,4',
      menuProcedure: [
        '1. Rebus daging masak agak empuk. Sisihkan air kaldunya, kemudian potong-potong daging sesuai selera.',
        '2. Tumis bawang bombai, kemudian masukkan bumbu halus. Masak hingga tanak.',
        '3. Masukkan potongan daging, aduk. Tambahkan kecap manis, saus tiram, kecap asin, saus tomat dan aduk rata.',
        '4. Masukkan air kaldu masak hingga air mengental dan daging empuk.',
        '5. Hidangkan.',
      ]),
  //Sayur
  Resep(
      menuId: 6,
      menuImage: 'assets/images/foods/resep/sayur0.png',
      menuName: 'Sayur Bobor Bayam',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp22.000',
      menuPreference: 'Sayur',
      menuDuration: '30 min',
      menuDescription:
          'Sayur bayam selalu identik dengan sayur bening. Namun, jika kamu bosan dengan sayur bening, bayam bisa diolah jadi bobor bayam, lho.',
      menuIngredients: [
        '2 ikat bayam (siangi)',
        '500 ml santan cair ',
        '400 ml santan kental',
        '100 gram kecambah kedelai',
        'Garam secukupnya',
        'Gula secukupnya',
        '5 siung bawang putih',
        '2 siung bawang merah',
        'Merica secukupnya'
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,4',
      menuProcedure: [
        '1. Siapkan sayur bayam yang sudah disiangi. Cuci lalu tiriskan. Begitu juga dengan kecambah kedelai.',
        '2. Panaskan wajan, tumis bawang putih dan bawang merah hingga aromanya harum. Jika sudah, tambahkan santan cair. Masak hingga hangat mendekati mendidih.',
        '3. Masukkan semua bumbu halus dan garam.',
        '4. Masukkan sayur bayam dan tunggu hingga agak layu. Tambahkan kecambah dan aduk hingga rata. Masak hingga semua bahan empuk dan mendidih.',
        '5. Tambahkan santan kental dan aduk hingga rata. Tambahkan gula dan penyedap rasa agar sayur bobor makin lezat serta nikmat.',
        '6. Biarkan hingga mendidih lalu angkat dan sajikan selagi hangat.',
      ]),
  Resep(
      menuId: 7,
      menuImage: 'assets/images/foods/resep/sayur1.png',
      menuName: 'Tumis Kankung',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp26.000',
      menuPreference: 'Sayur',
      menuDuration: '20 min',
      menuDescription:
          'Kangkung tumis atau kadang disebut tumis kangkung atau cah kangkung adalah hidangan sayur tumis yang lazim ditemukan dalam hidangan Asia.',
      menuIngredients: [
        '3 siung bawang putih, iris tipis',
        '2 siung bawang merah, iris tipis',
        '5 buah cabai rawit, iris serong',
        '3 buah cabai keriting, iris serong',
        'Garam secukupnya',
        'Gula secukupnya',
        'Kaldu jamur bubuk, secukupnya',
        'Penyedap masakan, secukupnya',
        'Merica secukupnya',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Siapkan semua bahan, panaskan minyak goreng. ',
        '2. Tumis bawang putih dan bawang merah hingga harum.',
        '3. Masukkan cabai rawit dan cabai keriting ke dalam tumisan bawang, aduk rata. Tumis hingga semua bumbu layu. ',
        '4. Masukkan sayur kangkung ke dalam wajan, aduk rata dan masak dengan api besar sambil terus diaduk. ',
        '5. Tambahkan garam, penyedap dan kaldu jamur bubuk. Aduk rata. ',
        '6. Tambahkan air panas sedikit saja, aduk rata.',
        '7. Koreksi rasa dan angkat tumis kangkung yang telah matang. Sajikan selagi masih hangat.',
      ]),
  Resep(
      menuId: 8,
      menuImage: 'assets/images/foods/resep/sayur2.png',
      menuName: 'Bening Kacang Panjang',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp24.000',
      menuPreference: 'Sayur',
      menuDuration: '30 min',
      menuDescription:
          'Resep Sayur bening kacang panjang mudah dan praktis. Buat kalian yang gak mau ribet dengan dunia permasakan.',
      menuIngredients: [
        '10 buah kacang panjang (potong panjang kira-kira 4 cm)',
        '50 gram kecambah kedelai (siangi)',
        '1 buah jagung muda (potong-potong sesuai selera)',
        '5 lembar daun kemangi',
        '3 cm rempah kunci (memarkan)',
        '5 siung bawang merah (iris tipis)',
        '3 siung bawang putih (memarkan)',
        'Gula pasir (secukupnya)',
        'Garam (secukupnya)',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Panaskan minyak (kira-kira 1 sdm) di wajan. ',
        '2. Tumis bawang merah dan bawang putih hingga aromanya harum. ',
        '3. Tambahkan air sesuai selera dan  masukkan kacang panjang serta kecambah kedelai.',
        '4. Masukkan pula garam, rempah kunci, daun kemangi dan jagung muda.',
        '5. Masak hingga semua bahan matang dan empuk. Tambahkan gula dan kaldu ayam bubuk agar rasa sayur bening makin gurih. ',
        '6. Jangan lupa untuk memasukkan buah tomat agar sayur bening ini makin segar.',
        '7. Masak hingga semua bahan masakan matang dan mendidih. ',
        '8. Jika sudah matang, angkat lalu sajikan.',
      ]),
  Resep(
      menuId: 9,
      menuImage: 'assets/images/foods/resep/sayur3.png',
      menuName: 'Sayur Urap',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp26.000',
      menuPreference: 'Sayur',
      menuDuration: '20 min',
      menuDescription:
          'Kangkung tumis atau kadang disebut tumis kangkung atau cah kangkung adalah hidangan sayur tumis yang lazim ditemukan dalam hidangan Asia.',
      menuIngredients: [
        '1 ikat kangkung',
        '1 ikat kacang panjang',
        '1 buah wortel',
        '1 genggam kecambah',
        '3 buah cabai merah',
        '3 buah cabai rawit',
        '1 ruas kencur',
        '1 cm terasi',
        '3 lembar daun jeruk',
        '2 siung bawang putih',
        '200 gr kepala parut',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,4',
      menuProcedure: [
        '1. Haluskan bumbu kelapa parut, campur dengan kelapa parut hingga rata. Bungkus dengan daun pisang. Kukus hingga matang atau kurang lebih 20 menit. ',
        '2. Potong-potong sayur dan rebus hingga matang, sisihkan.',
        '3. Masukkan cabai rawit dan cabai keriting ke dalam tumisan bawang, aduk rata. Tumis hingga semua bumbu layu. ',
        '4. Masukkan sayur kangkung ke dalam wajan, aduk rata dan masak dengan api besar sambil terus diaduk. ',
        '5. Campur kelapa parut bumbu dengan sayuran yang sudah direbus. ',
        '6. Sayur urap-urap siap dinikmati dengan ikan asin dan nasi hangat.',
        '7. Sajikan selagi masih hangat.',
      ]),
  Resep(
      menuId: 10,
      menuImage: 'assets/images/foods/resep/sayur4.png',
      menuName: 'Tumis Sawi Putih',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp26.000',
      menuPreference: 'Sayur',
      menuDuration: '20 min',
      menuDescription:
          'Kangkung tumis atau kadang disebut tumis kangkung atau cah kangkung adalah hidangan sayur tumis yang lazim ditemukan dalam hidangan Asia.',
      menuIngredients: [
        '3 siung bawang putih, iris tipis',
        '2 siung bawang merah, iris tipis',
        '5 buah cabai rawit, iris serong',
        '3 buah cabai keriting, iris serong',
        'Garam secukupnya',
        'Gula secukupnya',
        'Kaldu jamur bubuk, secukupnya',
        'Penyedap masakan, secukupnya',
        'Merica secukupnya',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Siapkan semua bahan, panaskan minyak goreng. ',
        '2. Tumis bawang putih dan bawang merah hingga harum.',
        '3. Masukkan cabai rawit dan cabai keriting ke dalam tumisan bawang, aduk rata. Tumis hingga semua bumbu layu. ',
        '4. Masukkan sayur kangkung ke dalam wajan, aduk rata dan masak dengan api besar sambil terus diaduk. ',
        '5. Tambahkan garam, penyedap dan kaldu jamur bubuk. Aduk rata. ',
        '6. Tambahkan air panas sedikit saja, aduk rata.',
        '7. Koreksi rasa dan angkat tumis kangkung yang telah matang. Sajikan selagi masih hangat.',
      ]),
  Resep(
      menuId: 11,
      menuImage: 'assets/images/foods/resep/sayur5.png',
      menuName: 'Tumis Kankung',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp26.000',
      menuPreference: 'Sayur',
      menuDuration: '20 min',
      menuDescription:
          'Kangkung tumis atau kadang disebut tumis kangkung atau cah kangkung adalah hidangan sayur tumis yang lazim ditemukan dalam hidangan Asia.',
      menuIngredients: [
        '3 siung bawang putih, iris tipis',
        '2 siung bawang merah, iris tipis',
        '5 buah cabai rawit, iris serong',
        '3 buah cabai keriting, iris serong',
        'Garam secukupnya',
        'Gula secukupnya',
        'Kaldu jamur bubuk, secukupnya',
        'Penyedap masakan, secukupnya',
        'Merica secukupnya',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Siapkan semua bahan, panaskan minyak goreng. ',
        '2. Tumis bawang putih dan bawang merah hingga harum.',
        '3. Masukkan cabai rawit dan cabai keriting ke dalam tumisan bawang, aduk rata. Tumis hingga semua bumbu layu. ',
        '4. Masukkan sayur kangkung ke dalam wajan, aduk rata dan masak dengan api besar sambil terus diaduk. ',
        '5. Tambahkan garam, penyedap dan kaldu jamur bubuk. Aduk rata. ',
        '6. Tambahkan air panas sedikit saja, aduk rata.',
        '7. Koreksi rasa dan angkat tumis kangkung yang telah matang. Sajikan selagi masih hangat.',
      ]),
  Resep(
      menuId: 24,
      menuImage: 'assets/images/foods/resep/roti0.jpg',
      menuName: 'Roti Gandum Vegan Oat',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp20.000',
      menuPreference: 'Roti',
      menuDuration: '12 min',
      menuDescription:
          'Resep Roi Gandum Vegan Oat. Buat kalian yang hobi makan roti tanpa ribet .',
      menuIngredients: [
        '200 gr terigu protein tinggi',
        '100 gr tepung gandum',
        '100 gr oat instan',
        '15 gr ragi instan',
        '75 gr gula pasir',
        '275 gr air hangat',
        '1/2 sdt garam',
        '50 ml olive oil / boleh ganti minyak goreng sepunya nya',
        '100 gr cranberry, rendam dengan air dingin, tiriskan',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Campur tepung terigu, tepung gandum, oat, ragi instan dan gula pasir. Aduk rata.',
        '2. Tuang air hangat sedikit demi sedikit dan aduk sampai kalis. ',
        '3. Tambahkan olive oil dan garam. Uleni sampai elastis. Jangan khawatir apabila adonan agak lengket atau lembek.',
        '4. Masukkan cranberry, aduk menyebar hingga rata, bulatkan, diamkan 30 menit.',
        '5. Kempiskan adonan, rolling dan gulung lipat sesuai dengan loyang masing masing. ',
        '6. Diamkan kembali selama 60 menit (fermentasi ke 2) atau sampai ukuran 2 kali lipat.',
        '7. Oles susu full cream, oven pada suhu 180 derajat selama kurang lebih 45 menit. Keluarkan dan sajikan. ',
      ]),
  Resep(
      menuId: 25,
      menuImage: 'assets/images/foods/resep/roti1.jpg',
      menuName: 'Sandwich Roti Gandum Avocado',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp22.000',
      menuPreference: 'Roti',
      menuDuration: '14 min',
      menuDescription:
          'Resep Roti Gandum Avocado yang membuat hari anda semakin cerah. Tanpa memerlukan waktu yang lama anda sudah dapat membuat roti yang nikmat!! .',
      menuIngredients: [
        '4 lembar roti gandum',
        '2 lembar daun selada',
        '4 iris tomat merah',
        '1 buah alpukat, potong 2 bagian',
        'irisan bawang merah besar secukupnya',
        '2 sendok makan mayonaise',
        '2 sendok makan margarin',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Telenan', 'Sendok'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Olesi kedua sisi roti gandum dengan margarin, lalu panggang dengan teflon hingga kecoklatan, sisihkan',
        '2. Ambil 1 lembar roti gandum, taruh daun selada di atasnya, lalu taruh irisan tomat, irisan bawang merah besar dan alpukat di atasnya ',
        '3. Ambil 1 lembar roti gandum yang lain, olesi satu sisinya dengan 1 sendok makan mayonaise, lalu tutup ke atas roti yang berisi sayuran di atas, ulangi untuk lembar roti gandum selanjutnya',
        '4. Potong roti yang telah diisi sayuran di atas menjadi 2 bagian, lalu sajikan.',
      ]),
  Resep(
      menuId: 26,
      menuImage: 'assets/images/foods/resep/roti2.jpg',
      menuName: 'Roti Gandum Isi Cokelat Rendah Kalori',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp24.000',
      menuPreference: 'Roti',
      menuDuration: '10 min',
      menuDescription:
          'Resep ini sangat cocok untuk anda yang sedang menjalankan program diet. Kalori yang ada pada roti ini tidak lebih dari 300 kkalori.',
      menuIngredients: [
        '50 gr coklat batang (70% kakao)',
        '50 gr tepung protein tinggi',
        '50 gr tepung gandum',
        '80 ml susu almond (bisa diganti susu kedelai)',
        '3 gr ragi',
        '2 gr garam',
        '1/2 sdt garam',
        '50 ml olive oil / boleh ganti minyak goreng sepunya nya',
        '8 gr butter',
      ],
      menuTools: [
        'Pisau',
        'Wajan datar',
        'Wadah untuk Roti',
        'Panggangan',
        'Cetakan'
      ],
      menuReview: '4.4',
      menuProcedure: [
        '1. Iris coklat batang tipis tipis dan kemudian cacah, sisihkan.',
        '2. Masukan terigu, gandum, dan ragi. Aduk rata ',
        '3. Tambahkan susu sedikit demi sedikit ulen hingga rata.',
        '4. Ulen adonan sampai setengah kalis. Tambahkan garam dan butter kemudian ulen hingga kalis.',
        '5. Bulatkan adonan dan simpan di wadah yang ditutup plastik atau kain basah dalam suhu ruang selama 60 menit.',
        '6. Setelah adonan mengembang 2x lipat, kempeskan dan bagi menjadi 5 bagian kemudian dibulatkan.',
        '7. Pipihkan dengan rolling pin kemudian isi dengan coklat, lalu digulung dan tutup bagian ujung ujungnya. ',
        '8. Diamkan lagi di wadah yang ditutup plastik sampai mengembang 2x lipat.',
        '9. Panggang 20-25 menit dalam oven dengan suhu 200C. '
      ]),

  Resep(
      menuId: 27,
      menuImage: 'assets/images/foods/resep/roti3.jpg',
      menuName: 'Roti Gandum Aneka Berry Kering dan Walnut',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp22.000',
      menuPreference: 'Roti',
      menuDuration: '13 min',
      menuDescription:
          'Resep ini sangat cocok untuk anda yang ingin belajar membuat roti dari dasarnya. Roti ini terbuat asli dari gandung dan dicampur adonan berry dan wallnut yang tentunya membuat rasa semakin menggugah selera anda!',
      menuIngredients: [
        '200 gr tepung protein tinggi',
        '200 gr tepung gandum halus',
        '100 gr tepung gandum ari',
        '1 butir telur',
        '50 gr susu bubuk',
        '6 gr garam',
        '1 bungkus/11 gr ragi',
        '280 ml susu cair',
        '1 sdm gula palem',
        '60 gr gula pasir',
        '80 gr margarin, saya pake palmia',
      ],
      menuTools: [
        'Loyang kue',
        'Telenan',
        'Wadah untuk Roti',
        'Panggangan',
        'Cetakan',
        'Sutil'
      ],
      menuReview: '4.4',
      menuProcedure: [
        '1. Campur ragi dan susu cair aduk lalu ditutup dengan kain. Diamkan dan tunggu sampai berbuih.',
        '2. Campur semua bahan menjadi 1 sampai rata dan uleni sampai kalis serta tidak nempel di tangan.',
        '3. Setelah itu istirahatkan adonan selama 1 jam. Setelah 1 jam ambil adonan, gilas agar udara di dalamnya hilang.',
        '4. Beri fillingnya sesuai selera, lalu di bentuk sesuai selera juga. Selanjutnya letakkan di loyang yang sudah di oles sedikit minyak olive atau pake kertas roti, dan diamkan lagi selama 1 jam hingga mengembang lagi.',
        '5. Panggang di oven selama 30-35 menit atau sesuai cara kerja oven masing-masing dengan suhu 180 derajat celcius.',
      ]),

  Resep(
      menuId: 28,
      menuImage: 'assets/images/foods/resep/roti4.jpg',
      menuName: 'Roti Sisir Gandum',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp20.000',
      menuPreference: 'Roti',
      menuDuration: '13 min',
      menuDescription:
          'Resep ini sangat cocok untuk anda yang ingin belajar membuat roti sisir kekinian! Anda akan dapat belajar dengan runtut bagaimana roti sisir dibuat ditambah dengan bumbu-bumbu masa kini!',
      menuIngredients: [
        '220 gr tepung protein tinggi',
        '30 gr tepung gandum',
        '20 gr creamer nabati',
        '30 gr gula pasir',
        '1/2 sdt garam',
        '170 gr air kelapa dingin kulkas kurang lebih 10C',
        '30 gr margarin',
        '4 gr instant yeast (ragi)',
        'Margarin untuk olesan',
      ],
      menuTools: [
        'Loyang kue',
        'Telenan',
        'Wadah untuk Roti',
        'Oven',
        'Cetakan'
      ],
      menuReview: '4.2',
      menuProcedure: [
        '1. Campur tepung, gula, creamer, garam dan air kelapa sampai setengah kalis, biarkan 1 jam dalam suhu ruang.',
        '2. Setelah 1 jam masukkan margarin dan yeast uleni 15 menit speed medium hingga kalis elastis.',
        '3.Lakukan windowpane test. Bila belum, tambah maksimum 5 menit tambahan.',
        '4. Adonan kalis elastis, diamkan selama 45 menit - 1 jam. Tutup dengan kain atau plastik wrap hingga double size.',
        '5. Tata di loyang, tutup dengan kain, biarkan fermentasi 45 menit-1 jam sampai double size.',
        '6. Panaskan oven 190C. Bake selama 20 menit (sesuaikan dengan oven masing-masing). Setelah matang segera oles dengan margarin selagi panas.'
      ]),

  Resep(
      menuId: 29,
      menuImage: 'assets/images/foods/resep/roti5.jpg',
      menuName: ' Kebab Roti Tawar',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp21.000',
      menuPreference: 'Roti',
      menuDuration: '9 min',
      menuDescription:
          'Resep ini akan mengajarkan kepada anda bagaimana membuat kebab yang praktis!! Anda tidak perlu jajan kebab diluar, dengan adanya resep ini anda akan dapat membuat kebab secara mandiri!',
      menuIngredients: [
        '5 lembar roti tawar',
        '2 siung bawang putih, rajang halus',
        '1 buah bawang bombay, iris tipis',
        '1 butir telur',
        '5 biji bakso (bisa diganti sosis)',
        'Bonggol jagung manis',
        '3 lembar daun selada',
        '1 sdt garam',
        '1 sdt gula',
        'Lada bubuk',
        '1 kaldu jamur',
        '2 sdm saus sambal',
        '2 sdm mayonaise',
      ],
      menuTools: [
        'Wajan',
        'Telenan',
        'Kompor',
        'Rolling pan/Botol kaca sirup',
        'Panggangan'
      ],
      menuReview: '4.2',
      menuProcedure: [
        '1. Tumis bawang putih dan bawang bombay sampai harum, masukkan telur lalu orak arik.',
        '2. Masukkan daun selada,jagung manis dan bakso (jangan diberi air).',
        '3.Tambahkan gula, garam, lada bubuk, dan kaldu jamur sesuai selera. Aduk rata. Matikan kompor.',
        '4. Iris pinggiran roti, lalu pipihkan roti menggunakan rolling pan (bisa pake botol kaca sirup).',
        '5. Isi roti dengan tumisan tadi, beri saus sambal dan mayonaise kemudian gulung rapi.',
        '6. Panggang roti di pan antilengket hingga kecokelatan (gunakan api kecil saja).',
        '7. Kebab penuh siap disajikan.'
      ]),

  Resep(
      menuId: 36,
      menuImage: 'assets/images/foods/resep/makananlaut0.png',
      menuName: 'Ikan Bakar Pedas',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp55.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '50 min',
      menuDescription:
          'Ikan bakar pedas sensasi ikan serasa pedas lava dimulut, rasa gurih yang bikin nagih dan terus nambah',
      menuIngredients: [
        '1 bungkus penyedap rasa ayam',
        '2 siung bawang merah, iris tipis',
        '10 buah cabai rawit, iris serong',
        '10 buah cabai keriting, iris serong',
        '1 sendok makan garam',
        "1 sendok makan minyak goreng"
      ],
      menuTools: [
        'Wajan datar',
        'Gelas ukur',
        'Panci',
        "Kompor",
        "Microwave",
        "Ulekan",
        "Pisau"
      ],
      menuReview: '4,8',
      menuProcedure: [
        '1. Cuci bersih ikan buang sisik dan isi perutnya.',
        '2. Lumuri ikan dengan air jeruk nipis biarkan 15 menit kemudian cuci kembali.',
        '3. Ulek kasar bumbu, campur dengan 1 sdm minyak goreng.',
        '4. Marinasi ikan dengan bumbu selama 30 menit dalam kulkas.',
        '5. Keluarkan ikan, bakar arang dan bakar ikan sampai matang sambil dioles sisa bumbu.',
      ]),

  Resep(
      menuId: 37,
      menuImage: 'assets/images/foods/resep/makananlaut1.png',
      menuName: 'Cumi Bakar Montok',
      menuPortion: '3 Porsi',
      menuPrice: 'Rp50.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '40 min',
      menuDescription:
          'Cumi Bakar Montok sensasi manis, asem, dan gurih, rasa gurih yang bikin nagih dan terus nambah',
      menuIngredients: [
        '1 buah cumi seberat 600gr',
        '1 sendok makan asam jawa',
        '1 gelas air',
        '3 udang kupas seberat 150 gr',
        '1 batang daun bawang kecil',
        "1 butir telur ayam",
        "2 sendok makan minyak goreng",
        "Garam secukupnya",
        'Garam secukupnya',
        "1 botol saus grill master hot dan crispy barbeque",
        "1 bungkus grill master seafood magic rub",
        "Garlic powder secukupnya",
        "Chilli Flakes secukupnya",
        "Basil Leaves secukupnya",
      ],
      menuTools: [
        'Gelas ukur',
        'Panci',
        "Kompor",
        "Microwave",
        "Ulekan",
        "Pisau"
      ],
      menuReview: '4,9',
      menuProcedure: [
        '1. Cuci bersih cumi, keluarkan telurnya, tiriskan badan dan kepalanya.',
        '2. Cincang kasar telur cumi dan udang, tuang dalam wadah.',
        '3. Tambahkan telur ayam yang sudah dikocok, daun bawang iris, garlic powder, garam, lada bubuk dan sedikit basil leaves.',
        '4. Lalu masukan ke dalam perut cumi, semat dengan lidi.',
        '5. Remas-remas asam jawa dengan air, buang ampasnya, tambahkan 1/2 pax grill master hot dan spicy barbeque, satu sendok makan grill master seafood magic rub, secukupnya chili flakes dan gula pasir.',
        "6. Aduk rata lalu marinade cumi beserta kepalanya kurang lebih 30 menit.",
        "7. Panaskan teflon, oles dengan minyak goreng, bakar cumi sambil dibolak balik dan diolesi bumbu marinade tadi."
            "8. Bakar sampai matang, angkat, potong-potong dan siap disajikan"
      ]),

  Resep(
      menuId: 38,
      menuImage: 'assets/images/foods/resep/makananlaut2.png',
      menuName: 'Kerang Hijau Saus Padang Pedas',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp35.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '30 min',
      menuDescription:
          'Kerang Hijau dimasak dengan saus khas Padang autentik. Rasa manisnya mampu bikin lidah anda bergoyang',
      menuIngredients: [
        '1 buah bawang bombai, diiris panjang',
        '1 sendok makan saus tiram',
        '3 sendok makan saus tomat',
        '4 sendok makan saus sambal',
        '1 botol air seberat 200 ml',
        "2 sendok makan margarin untuk menumis",
        "Garam, merica dan gula pasir secukupnya",
        "1 butir telur untuk mengentalkan",
        "3 buah cabai rawit",
        "3 buah cabai merah keriting",
      ],
      menuTools: [
        "Microwave",
        'Wajan Lonjong',
        'Sendok',
        'Panci',
        "Kompor",
        "Blender",
        "Ulekan",
        "Pisau"
      ],
      menuReview: '4,3',
      menuProcedure: [
        '1. Rebus kerang dalam air bersama daun salam sampai mendidih. Saring dan buang airnya. Pastikan tidak sampai kerang over cook, setelah dingin cabut serabut kerang agar bersih.',
        '2. Panaskan margarine, tumis bawang bombai, cabai rawit, dan bumbu halus sampai harum.',
        '3. Masukkan saus tiram, saus tomat, saus sambal, garam, merica bubuk, dan gula. Aduk rata. Tuang air. Masak sampai mendidih.',
        '4. Masukkan kerang, aduk rata.',
        '5. Masak sampai matang, Kentalkan dengan telur aduk rata.',
        '5. Masak sampai meletup-letup.',
        '5. Angkat dan sajikan.',
      ]),

  Resep(
      menuId: 39,
      menuImage: 'assets/images/foods/resep/makananlaut3.png',
      menuName: 'Tumis Kerang Dara pedas',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp30.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '20 min',
      menuDescription:
          'Kerang Dara ditumis dan dimasak dengan saus khas Manado. Rasa pedas dan manisnya mampu bikin bibir anda gonjor karena pedasnya',
      menuIngredients: [
        '1 lusin kerang dara rebus seberat 200 gram',
        '1 batang daun bawang, iris',
        '1 buah tomat, iris',
        '1 sendok teh garam',
        '1/2 sendok teh gula pasir',
        "13 buah cabai rawit, iris",
        "1 gelas air seberat 150 ml",
        "3 sendok makan saus tiram",
        "5 siung bawang putih, iris tipis",
        "7 siung bawang merah, iris tipis",
      ],
      menuTools: [
        'Wajan Lonjong',
        'Panci',
        'Sendok',
        "Blender",
        "Kompor",
        "Spatula",
        "Ulekan",
        "Pisau"
      ],
      menuReview: '4,5',
      menuProcedure: [
        '1. Panaskan sedikit minyak. Masukkan bawang merah, bawang putih, cabai, dan tomat. Tumis sampai harum.',
        '2. Masukkan kerang. Tambahkan air, gula, dan garam. Aduk rata.',
        '3. Tambahkan saus tiram dan daun bawang. Masak sampai bumbu meresap. Angkat dan sajikan.',
      ]),

  Resep(
      menuId: 40,
      menuImage: 'assets/images/foods/resep/makananlaut4.png',
      menuName: 'Asam Padeh Ikan',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp60.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '50 min',
      menuDescription:
          'Asam Padeh Ikan ditumis dan dimasak dengan saus khas Sumatera. Dengan rasa gurih dan pedas yang nampol dan bikin tubuh hangat',
      menuIngredients: [
        '2 ekor ikan salem',
        '3 buah tomat merah iris',
        '2 buah asam kandis',
        '1 batang serai geprek',
        '2 lembar daun salam',
        "3 lembar daun jeruk",
      ],
      menuTools: [
        'Panci',
        'Sendok',
        "Blender",
        "Pisau",
        "Spatula",
        "Ulekan",
        "Kompor",
        'Wajan Lonjong',
      ],
      menuReview: '4,4',
      menuProcedure: [
        '1. Masukkan dalam wajan bumbu halus, daun jeruk, salam, sere tambahkan air secukupnya lalu didihkan.',
        '2. Setelah mendidih masukkan ikan, asam kandis, beri garam secukupnya.',
        '3. Masak sampai kuah menyusut dan mengental.',
        "4. Terakhir koreksi rasa tambahkan irisan tomat dan sajikan."
      ]),

  Resep(
      menuId: 41,
      menuImage: 'assets/images/foods/resep/makananlaut5.png',
      menuName: 'Rajungan Saus Pedas',
      menuPortion: '1 Porsi',
      menuPrice: 'Rp80.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '60 min',
      menuDescription:
          'Rajungan saus pedas ditumis dan dimasak dengan saus khas Bandung. Dengan rasa gurih dan pedas yang nampol',
      menuIngredients: [
        '4 ekor rajungan',
        '1 buah bawang bombai, iris memanjang',
        '2 butir telur ukuran kecil, kocok lepas',
        '1 sendok makan kecap ikan',
        '1 sendok teh kecap manis',
        "1 sendok makan pasta cabai",
        "2 sendok makan saus sambal",
        "1 sendok makan saus tomat",
        "1/2 sendok teh merica bubuk",
        "100 ml air rebusan rajungan",
        "1 sendok teh perasan jeruk nipis",
        "Garam secukupnya",
        "5 siung bawang putih",
        "1 ruas jari jahe",
        "4 buah cabai merah besar"
      ],
      menuTools: [
        "Pisau",
        'Panci',
        "Kompor",
        'Sendok',
        "Blender",
        'Wajan Lonjong',
        "Spatula",
        "Ulekan",
      ],
      menuReview: '4,7',
      menuProcedure: [
        '1. Bersihkan kotoran rajungan dengan air mengalir.',
        '2. Didihkan air, kemudian masukkan rajungan, masak hingga matang (berubah warna menjadi merah), kemudian angkat dan tiriskan.',
        '3. Memarkan capit rajungan, cungkil cangkangnya agar bumbu bisa meresap nanti.',
        "4. Tumis bawang bombai hingga transparan, masukkan bumbu halus, saus sambal, saus tomat, merica, minyak ikan dan kecap manis, tumis hingga harum, masukkan air rebusan rajungan.",
        "5. Masukkan rajungan, kemudian masukkan kocokan telur agar bumbu mengental, masak dengan api kecil beberapa menit hingga bumbu meresap ke rajungan.",
        "6. Matikan api, lalu masukkan air jeruk nipis."
      ]),
];
